name: First-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name : Print Greetings
        run: echo "Hello World!"
      - name : Print bye
        run: echo "Good bye!!!" 
    
